import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="min-h-screen bg-surface-50 text-white px-5 py-24">
      <div className="max-w-3xl mx-auto">
        <Link to="/" className="text-brand-400 hover:text-brand-300 text-[13px] mb-12 inline-block font-medium">
          ← Back to Tubevo
        </Link>

        <h1 className="text-[32px] font-bold mb-3 tracking-tight">Terms of Service</h1>
        <p className="text-surface-600 text-[14px] mb-12">Last updated: February 23, 2026</p>

        <div className="space-y-10 text-surface-700 text-[14px] leading-relaxed">
          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Tubevo ("Service"), operated at tubevo.us, you agree to be
              bound by these Terms of Service. If you do not agree to these terms, do not use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">2. Description of Service</h2>
            <p>
              Tubevo is a SaaS platform that provides automated YouTube content creation and
              publishing tools, including AI-generated scripts, voiceovers, video assembly,
              and scheduled uploads to your YouTube channel.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">3. Account Registration</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>You must provide accurate and complete information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 18 years old to use this Service.</li>
              <li>One person or entity may not maintain more than one account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">4. Subscriptions & Payments</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Tubevo offers paid subscription plans (Starter, Pro, Agency) billed monthly.</li>
              <li>Payments are processed securely through Stripe.</li>
              <li>Subscriptions automatically renew unless cancelled before the renewal date.</li>
              <li>You may cancel your subscription at any time. Access continues until the end of the current billing period.</li>
              <li>Refunds are handled on a case-by-case basis. Contact support@tubevo.us for refund requests.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">5. YouTube & Google Integration</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>To use our upload features, you must connect your YouTube channel via Google OAuth.</li>
              <li>You grant Tubevo permission to upload videos to your YouTube channel on your behalf.</li>
              <li>You are responsible for ensuring all uploaded content complies with YouTube's Terms of Service and Community Guidelines.</li>
              <li>You may revoke Tubevo's access to your YouTube account at any time through your Google Account settings.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">6. Content & Intellectual Property</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Videos generated by Tubevo using AI tools are created for your use. You own the output content.</li>
              <li>Stock footage used in videos is sourced from licensed providers (e.g., Pexels) and is subject to their respective licenses.</li>
              <li>You are responsible for ensuring your content does not infringe on third-party intellectual property rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">7. Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Create content that is illegal, harmful, threatening, abusive, or hateful</li>
              <li>Violate YouTube's Terms of Service or Community Guidelines</li>
              <li>Spam or engage in deceptive practices</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">8. Limitation of Liability</h2>
            <p>
              Tubevo is provided "as is" without warranties of any kind. We are not liable for
              any indirect, incidental, special, or consequential damages arising from your use
              of the Service. Our total liability shall not exceed the amount you paid us in the
              12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account if you violate these
              Terms. You may delete your account at any time by contacting{' '}
              <a href="mailto:support@tubevo.us" className="text-brand-400 hover:text-brand-300 underline">
                support@tubevo.us
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">10. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-[18px] font-semibold text-white mb-4">11. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:support@tubevo.us" className="text-brand-400 hover:text-brand-300 underline">
                support@tubevo.us
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
